### ISSUE TITLE
unable to install deepdoctection[pt]

### ISSUE THREAD

**Issue by Erik-Ilavsky** [deepdoctection/deepdoctection#278] opened 2023-12-24 11:58 UTC
I try to install on ubuntu 20 lts, cpu version with:
apt-get -y install python3-pip git libgl1 libglib2.0-0
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
python3 -m pip install detectron2==0.6 -f   https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.10/index.html
pip3 install deepdoctection[pt]

there is problem with "ctypesgen: error: unrecognized arguments: --strip-build-path=/tmp/pip-install-61mmy9et/pypdfium2/data/bindings/headers --no-srcinfo" 

```
Requirement already satisfied: matplotlib>=3.1.0 in /usr/local/lib/python3.8/dist-packages (from python-doctr==0.7.0; extra == "pt"->deepdoctection[pt]) (3.7.4)
Collecting pypdfium2<5.0.0,>=4.0.0
  Using cached pypdfium2-4.25.0.tar.gz (138 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpwhksiy5y get_requires_for_build_wheel /tmp/tmpmvd_b3wf
       cwd: /tmp/pip-install-61mmy9et/pypdfium2
  Complete output (55 lines):
  usage: ctypesgen [-h] [--version] -i HEADERS [HEADERS ...] [-l LIBRARY] -o
                   FILE [--other-headers HEADER [HEADER ...]]
                   [-m MODULE [MODULE ...]] [-I INCLUDEDIR [INCLUDEDIR ...]]
                   [-L LIBDIR [LIBDIR ...]]
                   [--compile-libdirs LIBDIR [LIBDIR ...]]
                   [--runtime-libdirs LIBDIR [LIBDIR ...]]
                   [--no-system-libsearch] [--no-embed-preamble] [--cpp CPP]
                   [--allow-gnu-c] [-D MACRO [MACRO ...]] [-U NAME [NAME ...]]
                   [--save-preprocessed-headers FILENAME] [--optimize-lexer]
                   [-a] [--builtin-symbols] [--no-macros] [--no-undefs]
                   [--symbol-rules SYMBOL_RULES [SYMBOL_RULES ...]]
                   [--no-stddef-types] [--no-gnu-types] [--no-python-types]
                   [--no-load-library] [--insert-files FILENAME [FILENAME ...]]
                   [--output-language LANGUAGE]
                   [--dllclass {CDLL,WinDLL,OleDLL,PyDLL}] [--no-symbol-guards]
                   [--no-macro-guards] [--all-errors] [--show-long-errors]
                   [--no-macro-warnings] [--debug-level DEBUG_LEVEL]
  ctypesgen: error: unrecognized arguments: --strip-build-path=/tmp/pip-install-61mmy9et/pypdfium2/data/bindings/headers --no-srcinfo
  ['git', 'ls-remote', 'https://github.com/bblanchon/pdfium-binaries.git'] (cwd=None)
  Downloading binary 6191 ...
  Fetching chromium refs ...
  ['git', 'ls-remote', '--sort', '-version:refname', '--tags', 'https://chromium.googlesource.com/chromium/src', '*.*.*.0'] (cwd=None)
  Resolved 6191 -> PdfiumVer(major=122, minor=0, build=6191, patch=0)
  Downloading headers...
  Building bindings ...
  ['ctypesgen', '--strip-build-path=/tmp/pip-install-61mmy9et/pypdfium2/data/bindings/headers', '--library', 'pdfium', '--no-srcinfo', '--no-macro-guards', '--runtime-libdirs', '.', '--no-system-libsearch', '--compile-libdirs', '/tmp/pip-install-61mmy9et/pypdfium2/data/linux_x64', '--no-symbol-guards', '--symbol-rules', 'if_needed=\\w+_$|\\w+_t$|_\\w+', '--headers', 'fpdf_annot.h', 'fpdf_attachment.h', 'fpdf_catalog.h', 'fpdf_dataavail.h', 'fpdf_doc.h', 'fpdf_edit.h', 'fpdf_ext.h', 'fpdf_flatten.h', 'fpdf_formfill.h', 'fpdf_fwlevent.h', 'fpdf_javascript.h', 'fpdf_ppo.h', 'fpdf_progressive.h', 'fpdf_save.h', 'fpdf_searchex.h', 'fpdf_signature.h', 'fpdf_structtree.h', 'fpdf_sysfontinfo.h', 'fpdf_text.h', 'fpdf_thumbnail.h', 'fpdf_transformpage.h', 'fpdfview.h', '-o', '/tmp/pip-install-61mmy9et/pypdfium2/data/bindings/bindings.py'] (cwd=PosixPath('/tmp/pip-install-61mmy9et/pypdfium2/data/bindings/headers'))
  'https://github.com/bblanchon/pdfium-binaries/releases/download/chromium%2F6191/pdfium-linux-x64.tgz' -> '/tmp/pip-install-61mmy9et/pypdfium2/data/linux_x64/pdfium-linux-x64.tgz'
  Traceback (most recent call last):
    File "/tmp/tmpwhksiy5y", line 280, in <module>
      main()
    File "/tmp/tmpwhksiy5y", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpwhksiy5y", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-fw3pnchh/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-fw3pnchh/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-fw3pnchh/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 154, in <module>
    File "<string>", line 149, in main
    File "/tmp/pip-install-61mmy9et/pypdfium2/setupsrc/pypdfium2_setup/emplace.py", line 70, in prepare_setup
      _get_pdfium_with_cache(pl_name, pdfium_ver, flags, use_v8)
    File "/tmp/pip-install-61mmy9et/pypdfium2/setupsrc/pypdfium2_setup/emplace.py", line 45, in _get_pdfium_with_cache
      build_pdfium_bindings(req_ver, flags=req_flags, compile_lds=compile_lds)
    File "/tmp/pip-install-61mmy9et/pypdfium2/setupsrc/pypdfium2_setup/packaging_base.py", line 517, in build_pdfium_bindings
      run_ctypesgen(DataDir_Bindings, headers_dir, **kwargs)
    File "/tmp/pip-install-61mmy9et/pypdfium2/setupsrc/pypdfium2_setup/packaging_base.py", line 452, in run_ctypesgen
      run_cmd(args, cwd=headers_dir)
    File "/tmp/pip-install-61mmy9et/pypdfium2/setupsrc/pypdfium2_setup/packaging_base.py", line 399, in run_cmd
      comp_process = subprocess.run(command, cwd=cwd, check=check, **kwargs)
    File "/usr/lib/python3.8/subprocess.py", line 516, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['ctypesgen', '--strip-build-path=/tmp/pip-install-61mmy9et/pypdfium2/data/bindings/headers', '--library', 'pdfium', '--no-srcinfo', '--no-macro-guards', '--runtime-libdirs', '.', '--no-system-libsearch', '--compile-libdirs', '/tmp/pip-install-61mmy9et/pypdfium2/data/linux_x64', '--no-symbol-guards', '--symbol-rules', 'if_needed=\\w+_$|\\w+_t$|_\\w+', '--headers', 'fpdf_annot.h', 'fpdf_attachment.h', 'fpdf_catalog.h', 'fpdf_dataavail.h', 'fpdf_doc.h', 'fpdf_edit.h', 'fpdf_ext.h', 'fpdf_flatten.h', 'fpdf_formfill.h', 'fpdf_fwlevent.h', 'fpdf_javascript.h', 'fpdf_ppo.h', 'fpdf_progressive.h', 'fpdf_save.h', 'fpdf_searchex.h', 'fpdf_signature.h', 'fpdf_structtree.h', 'fpdf_sysfontinfo.h', 'fpdf_text.h', 'fpdf_thumbnail.h', 'fpdf_transformpage.h', 'fpdfview.h', '-o', '/tmp/pip-install-61mmy9et/pypdfium2/data/bindings/bindings.py']' returned non-zero exit status 2.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpwhksiy5y get_requires_for_build_wheel /tmp/tmpmvd_b3wf Check the logs for full command output.
```

**Comment by JaMe76** [comment] 2023-12-30 13:18
Looks like an installation issue for `pypdfium2`. Deepdoctection does not use this library (yet) but it will be installed along with DocTr. 

There is [this issue](https://github.com/pypdfium2-team/pypdfium2/issues/286) that seem to have the same error message for an `ubuntu:20.04` Docker container. Hope the comments provide some help.

**Comment by mara004** [comment] 2024-01-10 16:11
I still don't get the cause of this issue. Why are our wheels not recognized?
Perhaps because we don't use the legacy `manylinux2014` naming scheme?
I wonder whether `pip install -U pip packaging setuptools` would fix the issue?

**Closed** 2024-03-18 13:47 UTC
Labels: no-issue-activity, answered
